export { applyTheme, getCodeMirrorTheme, normalizeTheme } from "./apply"
export { getThemeDefinition, isValidTheme, themeRegistry, THEME_IDS } from "./registry"
export type { MascotId, ThemeDefinition, ThemeFx } from "./types"
export { ThemeAnimationBridge } from "./animation/ThemeAnimationBridge"
export { detectThemeFx, type ThemeFxInput } from "./animation/useThemeFx"
export { ThemeAppearanceSection } from "./components/ThemeAppearanceSection"
export { ThemeCardGrid } from "./components/ThemeCardGrid"
export { ThemeCompanionRail } from "./components/ThemeCompanionRail"
export { ThemeEmptyIllustration } from "./components/ThemeEmptyIllustration"
export { ThemeMascot } from "./components/ThemeMascot"
export { ThemeWatermark } from "./components/ThemeWatermark"